### ISSUE TITLE
Improve Sparklines

### ISSUE THREAD

**Issue by hamelsmu** [fastai/ghtop#2]
Recently @jph00 suggested to concatenate the freq to the histogram for the sparkline.  I didn't quite like my initial shot at this, which tended to have issues with the scale. 

Jeremy suggested to do this:

![image](https://user-images.githubusercontent.com/1483922/104133566-386f6d80-5339-11eb-8907-8582a54de099.png)

Other notes:

 - Currently there is a feature flag for Espark called `show_freq` that toggles the freq bit on or off
 - You probably want to add a parameter called y_lim or something

**Comment by hamelsmu** [comment]
Remaining items:

- [x] [Optional] See if you can get rid of first line
- [x] Make quota bar shorter, perhaps 8 characters wide
- [x] Use mn, mx and not ceil when setting limits on sparkline
- [x] Make user page take up full page
- [x] Add sparklines to user page

cc: @jph00

**Comment by hamelsmu** [comment]
ghtop tasks discussed on 1/15/2021

- [x] Verify that if you delete the token file `~/.ghtop_token` the auth prompt still works as expected
- [x]  Verify that the types filter actually filters the types.
- [x]  Make animated gif thing for README 
- [ ] Write a blog post about ghtop.  
- [x] Squash all the commits into one.

Needs discussion:

- [x] Investigate why the release counter does not appear to be incremented at all despite releases appearing on the screen.  **Proposed Solution show the total number of events for that interval (resets to zero at the end of the interval) I discussed this on slack**
- [x] Adjust the ylim in issues and PR sparklines.  **Hamel: the limit seems to be materially different during different times of day when I checked, perhaps we need a different solution? I don't have any amazing solutions to this problem, because its very context dependent**

**Comment by jph00** [comment]
> -[ ] Investigate why the release counter does not appear to be incremented at all despite releases appearing on the screen. *Proposed Solution show the total number of events for that interval (resets to zero at the end of the interval) I discussed this on slack*

Can you just add a decimal place for numbers<10?
>  * Adjust the ylim in issues and PR sparklines. *Hamel: the limit seems to be materially different during different times of day when I checked, perhaps we need a different solution? I don't have any amazing solutions to this problem, because its very context dependent*

Let's use a ylim suitable for a fairly busy peak time. That way, you know if it's unusually busy, which I think is the main thing.

**Comment by hamelsmu** [comment]
> Can you just add a decimal place for numbers<10?
> Let's use a ylim suitable for a fairly busy peak time. That way, you know if it's unusually busy, which I think is the main thing.

🚀 Done.

**Comment by hamelsmu** [comment]
# gifs

### quad

![ghtop](https://user-images.githubusercontent.com/1483922/105071141-0c3ea580-5a39-11eb-8808-34952c0bf26d.gif)

### tail

![ghtop-tail](https://user-images.githubusercontent.com/1483922/105073917-91778980-5a3c-11eb-9a4c-4532b8bd338f.gif)

**Comment by hamelsmu** [comment]
This is the one for tail

![ghtop-tail](https://user-images.githubusercontent.com/1483922/105073534-0a2a1600-5a3c-11eb-8327-88a0454ca871.gif)

**Comment by hamelsmu** [comment]
# Pictures

### tail

![image](https://user-images.githubusercontent.com/1483922/105074448-398d5280-5a3d-11eb-9603-3def521d87e5.png)

### quad

![image](https://user-images.githubusercontent.com/1483922/105074862-cb955b00-5a3d-11eb-99c5-3125bb98910b.png)


### simple

![image](https://user-images.githubusercontent.com/1483922/105074536-56298a80-5a3d-11eb-8e8c-32ba33e09405.png)

## users

![image](https://user-images.githubusercontent.com/1483922/105075363-8887b780-5a3e-11eb-9f7a-627268ac465f.png)

**Comment by hamelsmu** [comment]
Picture of simple

![image](https://user-images.githubusercontent.com/1483922/105074536-56298a80-5a3d-11eb-8e8c-32ba33e09405.png)

**Comment by hamelsmu** [comment]
# Ideas for things to focus on in blog

I think the interesting stuff about ghtop is the implementation

It's cool you can use plain python to consume an event stream like this
But behind the scenes it's actually off grabbing events in parallel for you!

It's an astonishingly small amount of code, and so easy to understand

Python's generators/iterators are really cool, and stuff like python's thread-safe queue make it easy to hide multithreading away from the user

Also, it's a nice-looking and fully-featured console app, which is amazingly easy to write and deploy in python, especially with nbdev and fastcore.script

I think a lot of people would be surprised how accessible it is to use all this cool tech

e.g. how would you have felt about implementing this a couple of years ago? would you expect it to be hard, and require external systems?


# My favorite idea:  Should open with this one 👇🏽 

I think a lot of people would be surprised how accessible it is to use all this cool tech

e.g. how would you have felt about implementing this a couple of years ago? would you expect it to be hard, and require external systems?
